### ISSUE TITLE
[feat] iA8tpcHwVtg missing transcript

### ISSUE THREAD

**Issue by helen-cheng** [dklassic/GDC-transcript#42]
**Checklist**

- [ ] This is a publicly available video from Game Developer Conference youtube channel
- [ ] There's no subtitle available for this video
- [ ] I've searched in issues and found no issue mentioning this video

**Additional context**
Add anything you want here.

**Comment by dklassic** [comment]
![IMG_0074](https://user-images.githubusercontent.com/9499899/235545363-f2ee3b0a-7ac2-450c-81d0-3726b3ad0d8c.jpeg)
Transcript exists, closing issue.
