### ISSUE TITLE
[feat] -ugdgGKE6IE missing transcript

### ISSUE THREAD

**Issue by ArkarNyuntWai** [dklassic/GDC-transcript#66]
**Checklist**

- [ ] This is a publicly available video from Game Developer Conference youtube channel
- [ ] There's no subtitle available for this video
- [ ] I've searched in issues and found no issue mentioning this video

**Additional context**
Add anything you want here.

**Comment by dklassic** [comment]
Hey, thanks for opening this issue but I don't think -ugdgGKE6IE is a GDC video? Please only open issue for GDC video.
