### ISSUE TITLE
[feat] e6-zbtDgDuw missing transcript

### ISSUE THREAD

**Issue by Sudipta-1997** [dklassic/GDC-transcript#84]
**Checklist**

- [ ] This is a publicly available video from Game Developer Conference youtube channel
- [x] There's no subtitle available for this video
- [ ] I've searched in issues and found no issue mentioning this video

**Additional context**
Add anything you want here.

**Comment by dklassic** [comment]
This repo is strictly for Game Developer Conference youtube channel.
